### ISSUE TITLE
WhenAny broken with DependencyProperty

### ISSUE THREAD

**Issue by bradphelan** [anaisbetts/reactiveui#1]
For the following dep prop used as a source for a WhenAny operation

```
#region Bound Property
/// <summary>
/// The logical rectangular boundary of the points set
/// </summary>
public Rect Bounds
{
    get { return (Rect)GetValue(BoundsProperty.DependencyProperty ); }
    set { SetValue(BoundsProperty, value); }
}

// Using a DependencyProperty as the backing store for Bounds.  This enables animation, styling, binding, etc...
public static readonly DependencyPropertyKey BoundsProperty =
    DependencyProperty.RegisterReadOnly(
        "Bounds", 
        typeof(Rect), 
        typeof(Mesh2D), 
        new PropertyMetadata(new Rect(0,0,0,0)));
#endregion
```

I get an exception

```
System.Windows.Markup.XamlParseException was unhandled
  HResult=-2146233087
  Message=The invocation of the constructor on type 'Weingartner.WPF.Mesh2D' that matches the specified binding constraints threw an exception.
  Source=PresentationFramework
  LineNumber=0
  LinePosition=0
  StackTrace:
            <snip>
  InnerException: System.InvalidCastException
       HResult=-2147467262
       Message=Unable to cast object of type 'System.Windows.DependencyPropertyKey' to type 'System.Windows.DependencyProperty'.
       Source=ReactiveUI.Xaml_Net45
       StackTrace:
            at ReactiveUI.Xaml.DependencyObjectObservableForProperty.<>c__DisplayClass4.<GetNotificationForProperty>b__1(IObserver`1 subj) in y:\HomeDirectoryStorage\SkyDrive\ReactiveUI_External\ReactiveUI.Xaml\DependencyObjectObservableForProperty.cs:line 61
            at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
            at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
            at System.Reactive.ExceptionHelpers.Throw(Exception exception)
            at System.Reactive.Stubs.<.cctor>b__1(Exception ex)
            at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
            at System.Reactive.Linq.Observable.CombineLatest`3._.S.OnError(Exception error)
            at System.Reactive.Linq.Observable.DistinctUntilChanged`2._.OnError(Exception error)
            at System.Reactive.Linq.Observable.Select`2._.OnError(Exception error)
            at System.Reactive.Linq.Observable.Where`1._.OnError(Exception error)
            at System.Reactive.Linq.Observable.Switch`1._.?.OnError(Exception error)
            at System.Reactive.Linq.Observable.Concat`1._.OnError(Exception error)
            at System.Reactive.Linq.Observable.Select`2._.OnError(Exception error)
            at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
            at System.Reactive.ObserverBase`1.Fail(Exception error)
            at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
            at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
            at System.Reactive.Linq.Observable.Select`2.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
            at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
            at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
            at System.Reactive.TailRecursiveSink`1.MoveNext()
            at System.Reactive.Concurrency.AsyncLock.Wait(Action action)
            at System.Reactive.TailRecursiveSink`1.<Run>b__0(Action self)
            at System.Reactive.Concurrency.Scheduler.<Schedule>b__45(Action`1 _action, Action`1 self)
            at System.Reactive.Concurrency.Scheduler.<>c__DisplayClass50`1.<InvokeRec1>b__4d(TState state1)
            at System.Reactive.Concurrency.Scheduler.InvokeRec1[TState](IScheduler scheduler, Pair`2 pair)
            at System.Reactive.Concurrency.ImmediateScheduler.Schedule[TState](TState state, Func`3 action)
            at System.Reactive.Concurrency.Scheduler.Schedule[TState](IScheduler scheduler, TState state, Action`2 action)
            at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action`1 action)
            at System.Reactive.TailRecursiveSink`1.Run(IEnumerable`1 sources)
            at System.Reactive.Linq.Observable.Concat`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
            at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
            at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
            at System.Reactive.Linq.Observable.Switch`1._.OnNext(IObservable`1 value)
            at System.Reactive.Linq.Observable.Select`2._.OnNext(TSource value)
            at System.Reactive.Linq.Observable.Return`1._.Invoke()
            at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
            at System.Reactive.Concurrency.ImmediateScheduler.Schedule[TState](TState state, Func`3 action)
            at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action)
            at System.Reactive.Linq.Observable.Return`1._.Run()
            at System.Reactive.Linq.Observable.Return`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
            at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
            at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
            at System.Reactive.Linq.Observable.Select`2.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
            at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
            at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
            at System.Reactive.Linq.Observable.Switch`1._.Run()
            at System.Reactive.Linq.Observable.Switch`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
            at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
            at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
            at System.Reactive.Linq.Observable.Where`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
            at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
            at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
            at System.Reactive.Linq.Observable.Select`2.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
            at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
            at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
            at System.Reactive.Linq.Observable.DistinctUntilChanged`2.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
            at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
            at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
            at System.Reactive.Linq.Observable.CombineLatest`3._.Run()
            at System.Reactive.Linq.Observable.CombineLatest`3.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
            at System.Reactive.Producer`1.Run(IScheduler _, State x)
            at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
            at System.Reactive.Concurrency.ScheduledItem`1.Invoke()
            at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
            at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
            at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
            at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
            at System.Reactive.Producer`1.Subscribe(IObserver`1 observer)
            at System.ObservableExtensions.Subscribe[T](IObservable`1 source, Action`1 onNext)
            at Weingartner.WPF.Mesh2D..ctor() in c:\Users\phelan\workspace\WeinCad.Net\WeinCad.WPF\Mesh2D.cs:line 160
       InnerException: 
```

**Comment by anaisbetts** [comment]
Nopenopenope, please move to ReactiveUI/ReactiveUI :)
